import 'project_data_model.dart';

final List<ProjectDataModel> companyProjects = [
  ProjectDataModel(
    name: '5paisa',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: '5paisa',
    companyLink: '',
    description: 'Stock trading and investment platform.',
  ),
  ProjectDataModel(
    name: 'altGraaf',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'altGraaf',
    companyLink: '',
    description: 'Alternative investment platform.',
  ),
  ProjectDataModel(
    name: 'Axis Mobile',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Axis Bank',
    companyLink: '',
    description: 'Banking app by Axis Bank.',
  ),
  ProjectDataModel(
    name: 'Axis Open Mobile App',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Axis Bank',
    companyLink: '',
    description: 'Open banking app experience by Axis.',
  ),
  ProjectDataModel(
    name: 'Canara AI1',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Canara Bank',
    companyLink: '',
    description: 'All-in-one banking app by Canara Bank.',
  ),
  ProjectDataModel(
    name: 'CRED',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'CRED',
    companyLink: 'https://cred.club',
    description: 'Credit card bill payments and rewards app.',
  ),
  ProjectDataModel(
    name: 'Dhan',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Dhan HQ',
    companyLink: '',
    description: 'Stock trading and investing app.',
  ),
  ProjectDataModel(
    name: 'Fampay',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Fampay',
    companyLink: '',
    description: 'Payments app for teens.',
  ),
  ProjectDataModel(
    name: 'Fyers',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Fyers',
    companyLink: '',
    description: 'Trading and investment platform.',
  ),
  ProjectDataModel(
    name: 'Hash For Gamers',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Hash',
    companyLink: '',
    description: 'Gaming finance and tracking app.',
  ),
  ProjectDataModel(
    name: 'HDFC Payzapp',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'HDFC Bank',
    companyLink: '',
    description: 'Digital payments and recharge app by HDFC.',
  ),
  ProjectDataModel(
    name: 'HDFC SKY',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'HDFC Securities',
    companyLink: '',
    description: 'Trading and investing app.',
  ),
  ProjectDataModel(
    name: 'ICICIDirect',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'ICICI Securities',
    companyLink: '',
    description: 'Investment and trading platform.',
  ),
  ProjectDataModel(
    name: 'IDFC FIRST Bank',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'IDFC FIRST',
    companyLink: '',
    description: 'Digital banking app.',
  ),
  ProjectDataModel(
    name: 'INDmoney',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'INDmoney',
    companyLink: '',
    description: 'Track and manage finances, investments, and credit.',
  ),
  ProjectDataModel(
    name: 'Jiraaf',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Jiraaf',
    companyLink: '',
    description: 'Fixed income investment platform.',
  ),
  ProjectDataModel(
    name: 'Kotak Neo',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Kotak Securities',
    companyLink: '',
    description: 'Mobile trading and investment app.',
  ),
  ProjectDataModel(
    name: 'Motilal Oswal Riise',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Motilal Oswal',
    companyLink: '',
    description: 'Investment app by Motilal Oswal.',
  ),
  ProjectDataModel(
    name: 'My Adani Gas',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Adani',
    companyLink: '',
    description: 'Gas and utility management app.',
  ),
  ProjectDataModel(
    name: 'N J Ewealth',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'NJ India Invest',
    companyLink: '',
    description: 'Wealth management platform.',
  ),
  ProjectDataModel(
    name: 'Nothing X',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Nothing',
    companyLink: '',
    description: 'Companion app for Nothing audio products.',
  ),
  ProjectDataModel(
    name: 'Post Office',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'India Post',
    companyLink: '',
    description: 'India Post banking and tracking app.',
  ),
  ProjectDataModel(
    name: 'Rail One',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'CRIS',
    companyLink: '',
    description: 'Railway ticket booking and tracking app.',
  ),
  ProjectDataModel(
    name: 'Rupeezy',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Rupeezy',
    companyLink: '',
    description: 'Trading and investing platform.',
  ),
  ProjectDataModel(
    name: 'SBI Securities',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'SBI Capital',
    companyLink: '',
    description: 'Trading platform by SBI.',
  ),
  ProjectDataModel(
    name: 'Sharekhan',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Sharekhan',
    companyLink: '',
    description: 'Investment and trading platform.',
  ),
  ProjectDataModel(
    name: 'Slice',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'Slice',
    companyLink: '',
    description: 'Credit card and payments app for millennials.',
  ),
  ProjectDataModel(
    name: 'Timepay',
    androidLink: '',
    iosLink: '',
    repoLink: '',
    creatorName: 'TimePay',
    companyLink: '',
    description: 'Payments and finance management app.',
  ),
];
