import 'project_data.dart';
import 'dart:io';

void main() {
  final buffer = StringBuffer();
  buffer.writeln('# 🚀 Awesome Flutter Projects (Auto-Generated)\n');
  buffer.writeln('> This file is automatically generated from Dart source.\n');

  final companies = flutterProjects.where((e) => e.type == 'company').toList();
  final personals = flutterProjects.where((e) => e.type == 'personal').toList();

  buffer.writeln('## 📱 Company Apps\n');
  companies.sort((a, b) => a.name.compareTo(b.name));
  for (var project in companies) {
    buffer.writeln(project.toMarkdown());
  }

  buffer.writeln('\n## 👨‍💻 Personal Projects\n');
  personals.sort((a, b) => a.name.compareTo(b.name));
  for (var project in personals) {
    buffer.writeln(project.toMarkdown());
  }

  File('README.md').writeAsStringSync(buffer.toString());
  print('✅ README.md generated');
}
